version: '3.8'

services:
  cash-game-tracker-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: cash-game-tracker-server:latest
    container_name: cash-game-tracker-server
    ports:
      - "8080:8080"
    environment:
      # Spring Boot configuration
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
